export const data = [
  { id: 1, food: "Sweet potatoes", nutrient: "Carbohydrates" },
  { id: 2, food: "Brown Rice", nutrient: "Carbohydrates" },
  { id: 3, food: "Lentils", nutrient: "Carbohydrates" },
  { id: 4, food: "Oatmeal", nutrient: "Carbohydrates" },
  { id: 5, food: "Navy Beans", nutrient: "Carbohydrates" },
  { id: 6, food: "Quinoa", nutrient: "Carbohydrates" },
  { id: 7, food: "Barley", nutrient: "Carbohydrates" },
  { id: 8, food: "Cassava", nutrient: "Carbohydrates" },
  { id: 9, food: "Turnips", nutrient: "Carbohydrates" },
  { id: 10, food: "Corn", nutrient: "Carbohydrates" },
  { id: 11, food: "Egg", nutrient: "Protein" },
  { id: 12, food: "Almond", nutrient: "Protein" },
  { id: 13, food: "Chicken", nutrient: "Protein" },
  { id: 14, food: "Milk", nutrient: "Protein" },
  { id: 15, food: "Cottage cheese", nutrient: "Protein" },
  { id: 16, food: "Carrot", nutrient: "Vitamins" },
  { id: 17, food: "Orange", nutrient: "Vitamins" },
  { id: 18, food: "Avocado", nutrient: "Vitamins" },
  { id: 19, food: "Cantaloupe", nutrient: "Vitamins" },
  { id: 20, food: "Kiwi", nutrient: "Vitamins" },
  { id: 21, food: "Bell pepper", nutrient: "Vitamins" },
  { id: 22, food: "Asparagus", nutrient: "Vitamins" },
  { id: 23, food: "Peanut", nutrient: "Vitamins" },
  { id: 24, food: "Pineapple", nutrient: "Vitamins" },
  { id: 25, food: "Cabbage", nutrient: "Vitamins" },
  { id: 26, food: "Pears", nutrient: "Fiber" },
  { id: 27, food: "Raspberries", nutrient: "Fiber" },
  { id: 28, food: "Sprouts", nutrient: "Fiber" },
  { id: 29, food: "Chia seeds", nutrient: "Fiber" },
  { id: 30, food: "Beans", nutrient: "Fiber" },
  { id: 31, food: "Shellfish", nutrient: "Iron" },
  { id: 32, food: "Spinach", nutrient: "Iron" },
  { id: 33, food: "Legumes", nutrient: "Iron" },
  { id: 34, food: "Red meat", nutrient: "Iron" },
  { id: 35, food: "Broccoli", nutrient: "Iron" },
  { id: 36, food: "Dried figs", nutrient: "Calcium" },
  { id: 37, food: "Soybeans", nutrient: "Calcium" },
  { id: 38, food: "Kale", nutrient: "Calcium" },
  { id: 39, food: "Sardines", nutrient: "Calcium" },
  { id: 40, food: "Shrimp", nutrient: "Calcium" },
  { id: 41, food: "Okra", nutrient: "Zinc" },
  { id: 42, food: "Pomegranate", nutrient: "Zinc" },
  { id: 43, food: "Guava", nutrient: "Zinc" },
  { id: 44, food: "Apricot", nutrient: "Zinc" },
  { id: 45, food: "Peaches", nutrient: "Zinc" },
  { id: 46, food: "Watermelon", nutrient: "Potassium" },
  { id: 47, food: "Mango", nutrient: "Potassium" },
  { id: 48, food: "Mushrooms", nutrient: "Potassium" },
  { id: 49, food: "Squash", nutrient: "Potassium" },
  { id: 50, food: "Papayas", nutrient: "Potassium" },
];
